#!/bin/bash

tput setaf 7; tput setab 4; tput bold
printf '%35s%s%-10s\n' "Change User Password"
tput sgr0
echo ""
echo -e "\033[1;33mLIST OF USERS AND THEIR PASSWORDS:\033[0m"
echo ""

# Get original user list (UID >= 1000, not 'nobody')
_original_users=($(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody))

# Prepare numbered map and password list
declare -A user_number_map
declare -A user_password_map
index=1
_userPass=""

for user in "${_original_users[@]}"; do
    num=$(printf "%02d" "$index")
    user_number_map["$user"]="$num"
    if [[ -e "/etc/DARKssh/senha/$user" ]]; then
        pass=$(< "/etc/DARKssh/senha/$user")
    else
        pass="Null"
    fi
    user_password_map["$user"]="$pass"
    _userPass+="\n$num:$user"
    ((index++))
done

# Sort usernames alphabetically for display
_sorted_users=($(printf "%s\n" "${_original_users[@]}" | sort))

# Display list
for user in "${_sorted_users[@]}"; do
    num="${user_number_map[$user]}"
    pass="${user_password_map[$user]}"
    suser=$(echo -e "\033[1;31m[\033[1;36m$num\033[1;31m] \033[1;37m- \033[1;32m$user\033[0m")
    ssenha=$(echo -e "\033[1;33mPassword\033[1;37m: $pass")
    printf '%-60s%s\n' "$suser" "$ssenha"
done

echo ""
read -p $'\033[1;32mEnter or select a user \033[1;33m[\033[1;36m01-N\033[1;33m]\033[1;37m: ' option
user=$(echo -e "$_userPass" | grep -E "^$option:" | cut -d: -f2)

if [[ -z $option || -z $user ]]; then
    tput setaf 7; tput setab 1; tput bold
    echo -e "\nInvalid selection or empty input!\n"
    tput sgr0
    exit 1
fi

if grep -q "^$user:" /etc/passwd; then
    echo -ne "\n\033[1;32mNew password for user \033[1;33m$user\033[1;37m: "
    read password
    sizepass=${#password}

    if [[ $sizepass -lt 2 ]]; then
        tput setaf 7; tput setab 1; tput bold
        echo -e "\nInvalid password! Use at least 2 characters.\n"
        tput sgr0
        exit 1
    fi

    if pgrep -u "$user" > /dev/null; then
        tput setaf 7; tput setab 4; tput bold
        echo -e "\nUser is logged in. Disconnecting..."
        tput sgr0
        pkill -u "$user"
    fi

    echo "$user:$password" | chpasswd
    echo "$password" > "/etc/DARKssh/senha/$user"

    tput setaf 7; tput setab 1; tput bold
    echo -e "\nUser password for $user has been changed to: $password\n"
    tput sgr0
    exit 0

else
    tput setaf 7; tput setab 4; tput bold
    echo -e "\nUser $user does not exist!\n"
    tput sgr0
    exit 1
fi
