#!/bin/bash

tput setaf 7; tput setab 4; tput bold
printf '%35s%s%-10s\n' "Change User Password"
tput sgr0
echo ""
echo -e "\033[1;33mLIST OF USERS AND THEIR PASSWORDS:\033[0m"
echo ""

# Get list of users with UID >= 1000, excluding nobody, and sort alphabetically
_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | sort)

i=0
unset _userPass

while read _user; do
    i=$((i + 1))
    _oP=$i
    [[ $i -lt 10 ]] && oP="0$i"

    if [[ -e "/etc/DARKssh/senha/$_user" ]]; then
        _senha=$(< "/etc/DARKssh/senha/$_user")
    else
        _senha='Null'
    fi

    suser=$(echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m")
    ssenha=$(echo -e "\033[1;33mPassword\033[1;37m: $_senha")
    printf '%-60s%s\n' "$suser" "$ssenha"

    _userPass+="\n${oP}:${_user}"
done <<< "$_userT"

num_user=$(echo "$_userT" | wc -l)

echo ""
echo -ne "\033[1;32mEnter or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: "
read option

user=$(echo -e "$_userPass" | grep -E "\b$option\b" | cut -d: -f2)

if [[ -z $option || -z $user ]]; then
    tput setaf 7; tput setab 1; tput bold
    echo -e "\nInvalid selection or empty input!\n"
    tput sgr0
    exit 1
fi

if grep -q "^$user:" /etc/passwd; then
    echo -ne "\n\033[1;32mNew password for user \033[1;33m$user\033[1;37m: "
    read password
    sizepass=${#password}

    if [[ $sizepass -lt 2 ]]; then
        tput setaf 7; tput setab 1; tput bold
        echo -e "\nInvalid password! Use at least 2 characters.\n"
        tput sgr0
        exit 1
    fi

    if pgrep -u "$user" > /dev/null; then
        tput setaf 7; tput setab 4; tput bold
        echo -e "\nUser is logged in. Disconnecting..."
        tput sgr0
        pkill -u "$user"
    fi

    echo "$user:$password" | chpasswd
    echo "$password" > "/etc/DARKssh/senha/$user"

    tput setaf 7; tput setab 1; tput bold
    echo -e "\nUser password for $user has been changed to: $password\n"
    tput sgr0
    exit 0

else
    tput setaf 7; tput setab 4; tput bold
    echo -e "\nUser $user does not exist!\n"
    tput sgr0
    exit 1
fi
