#!/bin/bash
#====================================================
#	SCRIPT: LIMITER DARKSSH MANAGER
#	DESENVOLVIDO POR:	CRAZY_VPN
#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
#	CANAL TELEGRAM:	http://t.me/darkssh
#====================================================
clear
database="/root/usuarios.db"
fun_multilogin() {
	(
		while read user; do
			[[ $(grep -wc "$user" $database) != '0' ]] && limit="$(grep -w $user $database | cut -d' ' -f2)" || limit='1'
			conssh="$(ps -u $user | grep sshd | wc -l)"
			[[ "$conssh" -gt "$limit" ]] && {
				pkill -u $user
			}
			
}
while true; do
    echo 'verificando...'
	fun_multilogin > /dev/null 2>&1
	sleep 15s
done
